#ifndef YHADIRERROR_H
#define YHADIRERROR_H
typedef enum RetCodetag
{
	Result_OK=0,					//0		SUCCESS
	Result_ERROR,					//1		一般错误
	ERROR_UNKNOWNSTATIONNAME,		//2		未知测试站名称
	ERROR_CURRENTOUTOFRANGE,		//3		电流超出范围
	ERROR_UNEXPECTEDCHARGER,		//4		不应有的充电器
	ERROR_FINDNOCHARGER,			//5		没发现充电器
	ERROR_TEMPRETUREADCOUTOFRANGE,	//6		温度超出范围
	ERROR_FREQERROR_TOOLARGE,		//7		AFC时频率误差太大
	ERROR_FREQERROR_TOONEAR,		//8     AFC时两个ADC值对应的频率误差太接近
	ERROR_FREQERROR_OUTOFRANGE,		//9		AFC时频率误差超出范围
	ERROR_TXPOWEROUTOFRANGE,		//10	发射功率超出范围
	ERROR_GSYS_SIZE,				//11	BRCM AGC时index超出GSYS_SIZE的范围
	ERROR_READGSYS,					//12	BRCM AGC时读取GSYS失败
	ERROR_FILENOTEXISTED,			//13	文件不存在
	ERROR_FILEOPENFAIL,				//14	打开文件失败
	ERROR_FILETOOSMALL,				//15	文件长度不够
	ERROR_FILEREADFAIL,				//16	读取文件失败
	ERROR_NOTACHIEVEEXPPOWER,		//17	无法校准到期望功率
	ERROR_NOSYNC,					//18	手机注册网络失败
	ERROR_NOCEST,					//19	与综测仪建立通话失败
	ERROR_BASECALLFAIL,				//20	综测仪发起呼叫失败
	ERROR_BASEENDCALLFAIL,			//21	综测仪结束通话失败
	ERROR_ENDCALLFAIL,				//22	结束通话失败
	ERROR_PEAKPOWEROUTOFRANGE,		//23	峰值功率超出范围
	ERROR_READPEAKPOWERERROR,		//24	综测仪读取峰值功率失败
	ERROR_FREQEEEROROUTOFRANGE,		//25	频率误差超出范围
	ERROR_READFREQERRORFAIL,		//26	综测仪读取频率误差失败
	ERROR_PEAKPHASEERROR,			//27	峰值相位误差超出范围
	ERROR_READPEAKPHASEERROR,		//28	综测仪读取峰值相位误差失败
	ERROR_RMSPHASEERROR,			//29	均方根相位误差超出范围
	ERROR_READRMSPHASEERROR,		//30	综测仪读取均方根相位误差失败
	ERROR_POSFLATTNESS,				//31	正平坦度超出范围
	ERROR_READPOSFLATTNESS,			//32	综测仪读取正平坦度失败
	ERROR_BANDHANDOVER,				//33	Bandhandover失败
	ERROR_NEGFLATTNESS,				//34	负平坦度超出范围
	ERROR_READNEGFLATTNESS,			//35	综测仪读取负平坦度失败
	ERROR_MODSPECTRUM,				//36	调制频谱超出范围
	ERROR_READMODSPECTRUM,			//37	综测仪读取调制频谱失败
	ERROR_SWTSPECTRUM,				//38	开关频谱超出范围
	ERROR_READSWTSPECTRUM,			//39	综测仪读取开关频谱失败
	ERROR_TIMEMASK,					//40	功率时间包络超出范围
	ERROR_READTIMEMASK,				//41	综测仪读取功率时间包络失败
	ERROR_RXLEVEL,					//42	接收电平超出范围
	ERROR_READRXLEVEL,				//43	综测仪读取接收电平失败
	ERROR_RXQUALITY,				//44	接收质量超出范围
	ERROR_READRXQUALITY,			//45	综测仪读取接收质量失败
	ERROR_RBERII,					//46	误码率超出范围
	ERROR_READRBERII,				//47	综测仪读取误码率失败
	ERROR_CRCOUTOFRANGE,			//48	循环冗余校验超出范围
	ERROR_READCRCOUTOFRANGE,		//49	综测仪测量CRC失败
	ERROR_MOBNORESPONSE,			//50	手机没有响应
	ERROR_MSGLENGTH,				//51	TAT消息长度错误
	ERROR_RETMSGSTRUCT,				//52	手机返回的消息结构错误
	ERROR_NOATRET,					//53	手机对AT指令无响应
	ERROR_BUFFERISNULL,				//54	缓冲区是空的
	ERROR_STOREBTMACFAIL,			//55	存储蓝牙MAC地址失败
	ERROR_BRCMON2PC,				//56	Intel打开BRCM端口失败
	ERROR_ENTERCALMODEFAIL,			//57	进入校准模式失败
	ERROR_GETRXLEVELFROMMOBILE,		//58	从手机读取接收电平失败
	ERROR_DOWNLOAD2PC,				//59	将BRCM切换到下载模式失败
	ERROR_PRESSKEY,					//60	模拟按键失败
	ERROR_STOREHWVER,				//61	存储硬件版本号失败
	ERROR_STORESTATIONFLAG,			//62	存储测试站信息失败
	ERROR_STORESN,					//63	存储手机序列号失败
	ERROR_STOREPRDSN,				//64	存储产品序列号
	ERROR_OPENCOMFAIL,				//65	打开串口失败
	ERROR_GETCOMSTATEFAIL,			//66	获取串口状态失败
	ERROR_SETCOMSTATEFAIL,			//67	设置串口状态失败
	ERROR_SETCOMTIMEOUTFAIL,		//68	设置串口超时状态失败
	ERROR_SETCOMMASKFAIL,			//69	设置COMMASK失败
	ERROR_SETUPCOMFAIL,				//70	SetupCom失败
	ERROR_PURGECOMFAIL,				//71	PurgeCom失败
	ERROR_COMNOTOPEN,				//72	串口未打开
	ERROR_SERIALPURGE,				//73	PurgeCom失败
	ERROR_CLEARCOMERRORFAIL,		//74	ClearComError失败
	ERROR_READCOMFAIL,				//75	读取串口失败
	ERROR_READNOCHAR,				//76	没有从串口读到值
	ERROR_SERIALPORTWRITE,			//77	写串口失败
	ERROR_SERIALWRITEDATA,			//78	未能向串口写入指定数量数据
	ERROR_GETNUMFAIL,				//79	从串口接收到的数据中获取数字失败
	ERROR_DIOEXCEPTION,				//80	DIO操作异常
	ERROR_DIOINITFAIL,				//81	DIO初始化失败
	ERROR_GENSIMLOCKIMGFAIL,		//82	生成SimLockImage失败
	ERROR_GENBOOTLOADERIMGFAIL,		//83	生成BootloaderImage失败
	ERROR_NOTREADENOUGHDATAFROMFILE,//84	未能从文件读到足够数据
	ERROR_SPEEDREQBYTE,				//85	没接收到串口速度请求
	ERROR_SPEEDCHGCONF,				//86	没接收到串口速度确认
	ERROR_ADDRESSWRONG,				//87	地址错误
	ERROR_IMGTOOLARGE,				//88	Image文件太大
	ERROR_DOWNLOADFAIL,				//89	下载失败
	ERROR_UNEXPECTEDCMDRECEIVED,	//90	接收到未知的命令
	ERROR_FOUNDNOTATMSGHEAD,		//91	没接收到TAT消息头
	ERROR_CAPTURENOTATMSG,			//92	没接收到TAT消息
	ERROR_SETRTCFAIL,				//93	设置RTC失败
	ERROR_DOUBLECHECKRTCFAIL,		//94	重新校验RTC失败
	ERROR_CHECKRTCFAIL,				//95	校验RTC失败
	ERROR_SETCHARGEMODEFAIL,		//96	设置手机进入充电模式失败
	ERROR_READCODECREGISTER,		//97	读取CODEC寄存器失败
	ERROR_WRITECODECREGISTER,		//98	写CODEC寄存器失败
	ERROR_CHECKDATA,				//99	校验从DOC Memory读出的数据失败
	ERROR_SDRAMCHECKFAIL,			//100	SDRAM测试失败
	ERROR_STARTBTFAIL,				//101	启动蓝牙失败
	ERROR_RESETBTFAIL,				//102	重置蓝牙失败
	ERROR_LASTSTATIONNOTPASS,		//103	上一站测试未通过
	ERROR_SNLENGTH,					//104	SN长度错误
	ERROR_INVALIDCHARINSN,			//105	SN中有无效字符
	ERROR_COPYFILE,					//106	拷贝文件错误
	ERROR_WRITEINI,					//107	写INI文件错误

	ERROR_GETAFCOFFSET,				//108	从手机读取频率误差失败
	ERROR_ZEROAFCOFFSET,			//109	从手机读取频率误差失败
	ERROR_AFCOFFSETOUTOFRANGE,		//110	AFC时频率误差超出范围
	ERROR_NORMINALAFCVALOUTOFRANE,	//111	AFC DAC超出范围
	ERROR_SLOPEPPBOUTOFRANGE,		//112	AFC直线斜率超出范围
	ERROR_READRSSI,					//113	读取RSSI错误
	ERROR_RSSILEVELTOOLOW,			//114	RSSI太小
	ERROR_AGC_NORACHIEVENPRMALLEVEL,//115	无法校准到期望的AGC Level
	ERROR_RSSIOUTOFRANGE,			//116	RSSI超出范围
	ERROR_ILLEGLEPHONENUMBER,		//117	非法的电话号码
	ERROR_COM_SENDSETUP,			//118	手机同步失败
	ERROR_EXIT_MODE,				//119	退出校准模式失败
	ERROR_PREPARE_PHASE,			//120	预校准失败
	ERROR_READ_BATTVOLT,			//121	从手机读取电池电压失败
	ERROR_SET_LCD_CONTRAST,			//122	设置LCD对比度失败
	ERROR_CALVALUE,					//123	擦除校准数据失败
	ERROR_LOAD_CALPARAM,			//124	读取CalParam失败
	ERROR_STORE_CALPARAM,			//125	存储CalParam失败
	ERROR_WRITE_CALPARAM,			//126	以YHT方式存储CalParam失败
	ERROR_DUMPMEMORY,				//127	DUMPMEMORY失败
	ERROR_SET_AFCDAC,				//128	Set AFC DAC失败
	ERROR_STORE_AFC,				//129	存储AFC结果失败
	ERROR_STORE_DCOFFSET,			//130	存储DC Offset失败
	ERROR_STORE_AGC,				//131	存储AGC数据失败
	ERROR_STORE_RSSI,				//132	存储RSSI失败
	ERROR_STORE_PWRRAMP,			//133	存储APC失败
	ERROR_STORE_TXFREQCOMP,			//134	存储频率补偿失败
	ERROR_STORE_BATTADC,			//135	存储Battery DAC失败
	ERROR_SET_GAIN,					//136	SetGainProgramData失败
	ERROR_SET_BANDMODE,				//137	设置频段模式失败
	ERROR_SET_RECVTRANSBURST,		//138	设置RecvTransBurst失败
	ERROR_SET_BURSTDATA,			//139	设置BurstData失败
	ERROR_SET_RAMP_SCALE_FACTOR,	//140	设置ScaleFactor失败
	ERROR_READ_RTCSTAT,				//141	读取RTC失败
	ERROR_SET_RXCONTROL,			//142	设置RxControl失败
	ERROR_WRITE_SIMINFO,			//143	写SIM卡信息失败
	ERROR_PROTOCOLSTATE,			//144	开关协议栈失败
	ERROR_AFM_SEND_BANDMODE,		//145	设置频段模式失败
	ERROR_SETBANDMODE_CALLTEST,		//146	设置频段模式
	ERROR_SIMLOCK,					//147	锁网失败
	ERROR_GET_AFC,					//148	读取AFC数据
	ERROR_GET_AGC,					//149	读取AGC数据
	ERROR_GET_RSSI,					//150	读取RSSI数据
	ERROR_GET_PWRRAMP,				//151	读取APC数据
	ERROR_VIBRATORTESTFAIL,			//152	震动测试失败
	ERROR_LEDTESTFAIL,				//153	LED测试失败
	ERROR_LOADHWVER,				//154	读取硬件版本号错误
	ERROR_LOADSN,					//155	读取序列号错误
	ERROR_GET_BOARDFLAG,			//156	读取测试站信息错误	
	ERROR_STORE_VCXO,				//157	存储VCXO错误
	ERROR_VCXO_MEAS,				//158	VCXO校准错误
	ERROR_TXCURRENTFAIL,			//159	发射电流超出范围
	ERROR_LCDBKLIGHTFAIL,			//160	LCD背光测试失败
	ERROR_READGPIOSTATUS,			//161	读取GPIO状态失败
	ERROR_INVALIDSDCARD,			//162	读取SD卡状态失败
	ERROR_STOREPRODUCTSN,			//163	存储产品SN失败
	ERROR_LOADPRODUCTSN,			//164	读取产品SN失败
	ERROR_STORECUSTOMERINFO,		//165	存储客户信息失败
	ERROR_LOADCUSTOMERINFO,			//166	读取客户信息失败
	ERROR_SETTIMINGADV,				//167	设置时间提前量失败
	ERROR_FER,						//168	帧擦除率超出范围
	ERROR_READFER,					//169	读取帧擦除率失败
	ERROR_BER,						//170	操作BER失败
	ERROR_READBER,					//171	读取BER失败
	ERROR_LOADSWVER,				//172	读取软件版本号错误
	ERROR_STOREFLAG,				//173	标志位存储错误
	ERROR_INVALIDIMGFILE,			//174	IMG文件名无效
	ERROR_WRONGSTATIONFLAG,			//175	测试站名称标志错误
	ERROR_INVALIDCHARINHWVER,		//176	硬件版本号中有无效字符
	ERROR_INVALIDCHARINSWVER,		//177	软件版本号中有无效字符
	ERROR_LOAD_TXFREQCOMP,          //178   读取频率补偿错误
	ERROR_SIM_UNLOCK,				//179   解锁出错
	ERROR_SIM_USER_CANCEL,          //180   遇到冲突，操作取消
	ERROR_SIM_PIN_ERROR,			//181   PIN码验证出错			
	ERROR_SIM_NOTLOCK,				//182   还没有加锁
	ERROR_LOADBTMACFAIL,			//183	读取蓝牙MAC地址失败//melancholic 20061121 a
	ERROR_RESTARTMOBFAIL,			//184	重启手机失败
	ERROR_UNCOMPATIBLEDRIVERLIB,	//185	测试函数库与当前系统不兼容
	ERROR_SETLOGSTATE,				//186	设置Log信息状态失败
	ERROR_LOADGPIBDRIVERDLL,		//187	装GPIB失败
	ERROR_WRONGGPIBCARDTYPE,		//188	错误的GPIB设备类型
	ERROR_GPIBSETTING,				//189	GPIB参数不正确失败
	ERROR_GETGPIBDEVICE,			//190	自动获取GPIB设备类型错误
	ERROR_GETDLLFUNCTION,			//191	装置DLL失败
	ERROR_GETGPIBTYPE,				//192	获取GPIB设备类型
	ERROR_OPENGPIBDEV,				//193	打开GPIB设备失败
	ERROR_READTIMINGADV,			//194	读取时间提前量失败
	ERROR_READBERA,					//195	读取bera失败
	ERROR_READBERB,					//196	读取berb失败
	ERROR_READCRC,					//197	读取CRC失败
	ERROR_READRBERA,				//198	读取Rbera失败
	ERROR_READRBERB,				//199	读取Rberb失败
	ERROR_READRCRC,					//200	读取RCRC失败
	ERROR_NO_OBJECT,				//201	没有成功创建对象
	ERROR_LOADVISADRIVERDLL,		//202	装VISA失败
	ERROR_WRONGPLATFORMTYPE,		//203	错误的平台
	ERROR_OPENPLATFORM,				//204	打开的平台失败
	ERROR_NORFDEFAULTFILE,			//205	射频配置文件default文件丢失
	ERROR_NORFCONFIGFILE,			//206	射频配置文件CONFIG文件丢失
	ERROR_SWITCHDEBUG,				//207	打开debug模式失败
	ERROR_CRYSTALAFCFAIL,			//208	Crystal AFC 失败
	ERROR_GETDEVVOLTAGE,			//209	读取设备电压失败
	ERROR_SETDEVVOLTAGE,			//210	设置设备电压失败
	ERROR_GETDEVCURRENT,			//211	读取设备电流失败
	ERROR_SETDEVCURRENT,			//212	设置设备电流失败
	ERROR_BATT_ADC_Slop_Offset_FAIL,//213	ADC SLOPE 和 Offset计算失败
	ERROR_CHAR_ADC_Slop_Offset_FAIL,//214	ADC SLOPE 和 Offset计算失败
	ERROR_BATT_CHAN_Slop_FAIL,		//215	Check Battey Channel Slop Failed
	ERROR_BATT_CHAN_Offset_FAIL,	//216	Check Battey Channel Offset Failed
	ERROR_ADC_Cal_Curr_FAIL,		//217	ADC Calibration Curr difference
	ERROR_ADC_Cal_Volt_FAIL,		//218	ADC Calibration voltage difference
	ERROR_AGC_Cal,					//219	AGC 校准失败
	ERROR_AGC_Check,				//220	AGC 校准检验失败
	ERROR_GET_IQImbalance,			//221	IQImbalance读取失败
	ERROR_GET_OriginalOffset,		//222	OriginalOffset读取失败
	ERROR_APC_Check_Fail,			//223	APC 检查失败
	ERROR_TXIQ_EDGE_FAIL,			//224	TXIQ EDGE 校准失败
	ERROR_GET_EDGEIQImbalance,		//225	edge IQImbalance读取失败
	ERROR_GET_EDGEOffset,			//226	edge OriginalOffset读取失败
	ERROR_APC_EDGE_Check_Fail,		//227	edge APC check
	ERROR_APC_SWING,				//228	功率左右波动无法校准上
	ERROR_READ_EDGEOVER,			//229	无法读取Edge Overview
	ERROR_READ_EDGEBER,				//230	无法读取EDGE的BER
	ERROR_SET_DLULPARA,				//231	设置上下行的参数错误
	ERROR_READ_IMEI,				//232	读取IMEI错误
	ERROR_WRITE_IMEI,				//233	写入IMEI错误
	ERROR_NO_APC_METHOD,			//234	没有APC相关校准算法
	ERROR_AFC_CW_FAIL,				//235	AFC的CW校准算法出现错误
	ERROR_EXIST_IMEI,				//236	已存在IMEI，不允许重复写入
	ERROR_WIFIMACILLEGAL,			//237	写入WIFI地址失败
}RetCode;

#define ASSERTRES(res) if((res)!=Result_OK){return (res);}
#endif
